### ISSUE TITLE
Investigate webcomponents

### ISSUE THREAD

**Issue by wimdeblauwe** [wimdeblauwe/htmx-spring-boot-thymeleaf#28]
Not sure if it belongs in this library, since it is not strictly tied to htmx, but I wonder if we could support webcomponents like https://github.com/EmilStenstrom/django-components and https://viewcomponent.org/ do. This ticket is just for gathering ideas and links around this for now.

https://lit.dev/ might also be interesting.

**Comment by checketts** [comment]
I'm looking into using Flowbite (with Tailwind CSS) templates and extracting those into reusable templates that I can use in Thymeleaf (and HTMX). Perhaps I'll learn something useful.

**Comment by wimdeblauwe** [comment]
This problem is being solved very nicely at https://github.com/tschuehly/spring-view-component
