### ISSUE TITLE
hx-get (post. etc...) can't work with th:fragment return

### ISSUE THREAD

**Issue by hant35** [wimdeblauwe/htmx-spring-boot-thymeleaf#40]
When I return html by fragment (EX:  "/tour/sub/detail :: dayFragment" ) then hx-get in fragment (dayFragment) can not run.

**Comment by wimdeblauwe** [comment]
Can you elaborate on what exactly you are trying to do and what does not work? What do you mean exactly with "hx-get can not run"?

**Comment by wimdeblauwe** [comment]
Closing due to missing information. Feel free to re-open if you can give more information.
