### ISSUE TITLE
Remove System.out.println

### ISSUE THREAD

**Issue by wimdeblauwe** [wimdeblauwe/htmx-spring-boot-thymeleaf#47]
`HtmxHandlerMethodArgumentResolver` has:
```
System.out.println("nativeRequest = " + nativeRequest);
```

which should be removed.

**Comment by Harsh4902** [comment]
Can I work on this issue?

**Comment by wimdeblauwe** [comment]
Sure

**Comment by wimdeblauwe** [comment]
https://github.com/wimdeblauwe/htmx-spring-boot-thymeleaf/releases/tag/2.1.0 released with this change. Thank you for your contribution!
