### ISSUE TITLE
Preserve the order of templates inside HtmxResponse

### ISSUE THREAD

**Issue by klu2** [wimdeblauwe/htmx-spring-boot-thymeleaf#48]
The `HtmxResponse` currently stores its templates inside a `Set`, so the order is not preserved. Although stated differently in the docs of HTMX, the order might be relevant in some edge-cases, see https://github.com/bigskysoftware/htmx/issues/1198.

I'd therefore suggest to change the implementeion to use a `LinkedHashSet` instead of a `HashSet`, it seems also more intuitive when debugging the generated responses.

**Comment by wimdeblauwe** [comment]
https://github.com/wimdeblauwe/htmx-spring-boot-thymeleaf/releases/tag/2.1.0 released with this change. Thank you for your contribution!
